apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: index.docker.io/flicker/test-1:helloworld3
        name: helloworld
        ports:
        - containerPort: 9999
