name: learn-github-actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          STRING1: ${{ secrets.PASSWORD1 }}
        run: |
          echo "--> $STRING1" > output.log
